### ISSUE TITLE
BSGD execution

### ISSUE THREAD

**Issue by martisaju** [ruivieira/spark-als-streaming#1]
Hello @ruivieira , amazing project!

I am developing a project where I have a R matrix that I have factorized (without biases) using the ALS method. Then, new ratings (from previously seen interactions between users and products) arrive periodically.

I have some doubts regarding the management of the new incoming ratings and the biases.
- About the global bias, how do you initialize it? I have assigned the mean value of all the ratings that appear at the R matrix, does it make sense?
- For the user and product biases that appear at the updating process for the Ux and Py matrices, do you initialize them randomly?
- How do you manage the incoming rating to calculate the prediction error? I don't understand how the new rating is inferred at the BSGD formula.

Thank you very much for your help

**Comment by ruivieira** [comment]
Thank you, @martisaju.

- Global bias: yes, the mean of existing ratings is a typical initialisation value
- You can initalise all user and product bias to zero or random values, and then update them individually with new data with the prediction error weighted by the learning rate.
- The new incoming rating for user `x` and product `y` would have a predicted rating `^R(x,y)=b+b_x+b_y+𝖴^T_x * 𝖯_y`, the error is between `^R(x,y)` and the actual `R(x,y)`.

This is explained with more detail in this blog post: https://ruivieira.dev/a-streaming-als-implementation.html

**Comment by martisaju** [comment]
Thank you, @ruivieira 👍

**Comment by martisaju** [comment]
Hello @ruivieira , 

I am reopening the issue because I am facing some problems during the uploading phase of the user and product latent factors. 

As I said, I am just receiving a single rating from previously seen user and product. I am following the procedure you explain in the blog post (that is awesome), but once I have both user_factors, product_factors and their biases uploaded I calculate the RMSE value between the predicted rating (`^R(x,y)=b+b_x+b_y+𝖴^T_x * 𝖯_y`) and the rating that has arrived. Then I iterate again until this error is stable. The problem I am facing is that the error increases at each iteration . I have tried to change both the learning rate parameter and the regularization factor but I cannot get better results. Do you know the reason(s) of the trouble I am facing?
Thanks, again.
